application: pucktracker
version: 1
runtime: python27
api_version: 1
threadsafe: true  # TODO ok?

handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: .*
  script: application.app

- url: /static
  static_dir: application/static

libraries:
- name: lxml
  version: latest

builtins:
- deferred: on
- remote_api: on